version: '3.8'
services:
  iris:
    init: true
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 41773:1972
      - 42773:52773
      - 53773
    volumes:
      - ./:/irisdev/app
#    environment:
#      - PYTHONHOME=/usr
